sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3307
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tGbgnYqUZy3Fzgiid5U
    access-key-secret: oD9jUaTbT90bkAX5vQrBVSLWYyeIYi
    bucket-name: skyeatout
